server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train_21995?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B7
    username: root
    password: Mysql123
mybatis:
  type-aliases-package: com.hand.train.po
  mapper-locations: classpath:mapper/*Mapper*.xml
logging:
  level:
    com.hand.train: debug